version: "3.9"

services:
  zendown-ai:
    image: ghcr.io/rishikanthc/zendown-ai:v0.1.0
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./db:/db
    environment:
      - LANCEDB_URI=/db
    restart: unless-stopped
    # Optionally: command override here if you want (by default uses Dockerfile CMD)

