version: "3.9"

services:
  zendown-ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./db:/db
    environment:
      - LANCEDB_URI=/db
    # Optionally: restart: unless-stopped
    # Optionally: command override here if you want (by default uses Dockerfile CMD)

